BEGIN;

-- --------------------------------------------------
-- ITAM SCHEMA DEFINITIONS FOR SUPABASE / POSTGRES
-- --------------------------------------------------

CREATE TABLE IF NOT EXISTS "inventory_asset" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "type" varchar(20) NOT NULL,
    "serial_number" varchar(100) NOT NULL UNIQUE,
    "status" varchar(30) NOT NULL,
    "date_created" timestamp with time zone NOT NULL,
    "created_by_id" integer NULL REFERENCES "auth_user" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "inventory_employee" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "department" varchar(255) NOT NULL,
    "email" varchar(254) NOT NULL UNIQUE,
    "user_id" integer NULL UNIQUE REFERENCES "auth_user" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "inventory_assignment" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "date_assigned" timestamp with time zone NOT NULL,
    "expected_return_date" date NULL,
    "date_returned" timestamp with time zone NULL,
    "confirmed_by_employee" boolean NOT NULL DEFAULT FALSE,
    "confirmed_at" timestamp with time zone NULL,
    "asset_id" bigint NOT NULL REFERENCES "inventory_asset" ("id") ON DELETE PROTECT,
    "employee_id" bigint NOT NULL REFERENCES "inventory_employee" ("id") ON DELETE PROTECT,
    "created_by_id" integer NULL REFERENCES "auth_user" ("id") ON DELETE SET NULL,
    "return_requested" boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "inventory_maintenancelog" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "issue_description" text NOT NULL,
    "technician" varchar(255) NOT NULL,
    "repair_shop" varchar(255) NOT NULL DEFAULT '',
    "worker_contact" varchar(255) NOT NULL DEFAULT '',
    "expected_completion_date" date NULL,
    "date" date NOT NULL,
    "resolved" boolean NOT NULL DEFAULT FALSE,
    "asset_id" bigint NOT NULL REFERENCES "inventory_asset" ("id") ON DELETE CASCADE,
    "created_by_id" integer NULL REFERENCES "auth_user" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "inventory_assetcatalog" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL UNIQUE,
    "created_at" timestamp with time zone NOT NULL,
    "created_by_id" integer NULL REFERENCES "auth_user" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "inventory_catalogasset" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "type" varchar(20) NOT NULL,
    "serial_number" varchar(100) NOT NULL,
    "status" varchar(30) NOT NULL,
    "last_maintenance_date" date NULL,
    "imported_at" timestamp with time zone NOT NULL,
    "catalog_id" bigint NOT NULL REFERENCES "inventory_assetcatalog" ("id") ON DELETE CASCADE,
    CONSTRAINT "catalog_asset_serial_unique" UNIQUE ("catalog_id", "serial_number")
);

CREATE TABLE IF NOT EXISTS "inventory_employeenotification" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "type" varchar(20) NOT NULL DEFAULT 'info',
    "title" varchar(150) NOT NULL,
    "message" text NOT NULL,
    "link" varchar(255) NOT NULL DEFAULT '',
    "read" boolean NOT NULL DEFAULT FALSE,
    "created_at" timestamp with time zone NOT NULL,
    "employee_id" bigint NOT NULL REFERENCES "inventory_employee" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "inventory_adminnotification" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "type" varchar(20) NOT NULL DEFAULT 'info',
    "title" varchar(150) NOT NULL,
    "message" text NOT NULL,
    "link" varchar(255) NOT NULL DEFAULT '',
    "read" boolean NOT NULL DEFAULT FALSE,
    "created_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "inventory_backgroundjob" (
    "id" uuid NOT NULL PRIMARY KEY,
    "job_type" varchar(32) NOT NULL,
    "status" varchar(16) NOT NULL DEFAULT 'pending',
    "priority" smallint NOT NULL DEFAULT 50,
    "params" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "result" jsonb NULL,
    "error_message" text NOT NULL DEFAULT '',
    "result_file" varchar(100) NOT NULL DEFAULT '',
    "created_at" timestamp with time zone NOT NULL,
    "started_at" timestamp with time zone NULL,
    "completed_at" timestamp with time zone NULL,
    "user_id" integer NOT NULL REFERENCES "auth_user" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "inventory_userprofile" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "avatar_url" varchar(500) NOT NULL DEFAULT '',
    "avatar_storage_key" varchar(255) NOT NULL DEFAULT '',
    "avatar_storage_backend" varchar(20) NOT NULL DEFAULT '',
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") ON DELETE CASCADE
);

-- --------------------------------------------------
-- INDEXES FOR FASTER LOOKUPS
-- --------------------------------------------------

CREATE INDEX IF NOT EXISTS "asset_status_idx" ON "inventory_asset" ("status");
CREATE INDEX IF NOT EXISTS "asset_type_idx" ON "inventory_asset" ("type");
CREATE INDEX IF NOT EXISTS "asset_created_idx" ON "inventory_asset" ("date_created");
CREATE INDEX IF NOT EXISTS "asset_status_type_idx" ON "inventory_asset" ("status", "type");
CREATE INDEX IF NOT EXISTS "asset_name_serial_idx" ON "inventory_asset" ("name", "serial_number");

CREATE INDEX IF NOT EXISTS "employee_name_idx" ON "inventory_employee" ("name");
CREATE INDEX IF NOT EXISTS "employee_department_idx" ON "inventory_employee" ("department");
CREATE INDEX IF NOT EXISTS "employee_email_idx" ON "inventory_employee" ("email");

CREATE INDEX IF NOT EXISTS "assignment_asset_return_idx" ON "inventory_assignment" ("asset_id", "date_returned");
CREATE INDEX IF NOT EXISTS "assignment_emp_return_idx" ON "inventory_assignment" ("employee_id", "date_returned");
CREATE INDEX IF NOT EXISTS "assignment_asset_date_idx" ON "inventory_assignment" ("asset_id", "date_assigned" DESC);
CREATE INDEX IF NOT EXISTS "assignment_emp_date_idx" ON "inventory_assignment" ("employee_id", "date_assigned" DESC);
CREATE INDEX IF NOT EXISTS "assignment_emp_confirm_idx" ON "inventory_assignment" ("employee_id", "confirmed_by_employee");

CREATE INDEX IF NOT EXISTS "maintenance_asset_date_idx" ON "inventory_maintenancelog" ("asset_id", "date" DESC);
CREATE INDEX IF NOT EXISTS "maintenance_date_idx" ON "inventory_maintenancelog" ("date");
CREATE INDEX IF NOT EXISTS "maintenance_resolved_idx" ON "inventory_maintenancelog" ("resolved", "date");

CREATE INDEX IF NOT EXISTS "employee_notif_unread_idx" ON "inventory_employeenotification" ("employee_id", "read", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "admin_notif_unread_idx" ON "inventory_adminnotification" ("user_id", "read", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "bgjob_status_prio_idx" ON "inventory_backgroundjob" ("status", "priority" DESC, "created_at");
CREATE INDEX IF NOT EXISTS "bgjob_user_type_idx" ON "inventory_backgroundjob" ("user_id", "job_type", "created_at" DESC);

COMMIT;
