# Generated by Django 5.1.3 on 2026-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_date_created'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['type'], name='asset_type_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['date_created'], name='asset_created_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'type'], name='asset_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name', 'serial_number'], name='asset_name_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['asset', 'date_returned'], name='assignment_asset_return_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['employee', 'date_returned'], name='assignment_emp_return_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['asset', '-date_assigned'], name='assignment_asset_date_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['employee', '-date_assigned'], name='assignment_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='employee_name_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employee_department_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employee_email_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['asset', '-date'], name='maintenance_asset_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['date'], name='maintenance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['resolved', 'date'], name='maintenance_resolved_idx'),
        ),
    ]
