# Generated by Django 5.2.15 on 2026-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_backgroundjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('reports', 'Reports analytics'), ('asset_sections', 'Asset list sections'), ('dashboard', 'Dashboard metrics'), ('csv_export', 'Asset CSV export'), ('serial_suggestions', 'Asset serial number suggestions')], max_length=32),
        ),
    ]
