# Generated by Django 5.1.3 on 2026-07-06 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_backgroundjob_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_catalogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Router', 'Router'), ('Monitor', 'Monitor')], max_length=20)),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=30)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory.assetcatalog')),
            ],
            options={
                'ordering': ['name', 'serial_number'],
                'constraints': [models.UniqueConstraint(fields=('catalog', 'serial_number'), name='catalog_asset_serial_unique')],
            },
        ),
    ]
