# Generated by Django 5.1.3 on 2026-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_storage_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
    ]
